#!/bin/bash

URL="${1}"
FILE_NAME="${2}"

echo "Starting ${FILE_NAME}"

# Basic URL encoding. More robust solutions don't seem to work well in bash.
URL=`echo "${URL}" | sed "s/\&/\&amp;/g"`

V=`cat <<HEREDOC
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>URL</key>
  <string>$URL</string>
</dict>
</plist>
HEREDOC`

echo -n "${V}" > "$FILE_NAME"

echo "Done ${FILE_NAME}"