#!/bin/bash

if [ "$#" -lt "1" ]
then
  SCRIPT_NAME=$(basename "${0}")
  echo "Usage: ${SCRIPT_NAME} in-file.anything [out-file.wav]"
  exit 1
fi

OUT_FILE="${2}"

if [ -z "${OUT_FILE}" ]
then
  OUT_FILE="${1}.wav"
fi

ffmpeg -i "${1}" -f wav "${OUT_FILE}" 2>&1 | grep -E "Input|Output|Stream"