#!/bin/bash

# Old. Doesn't detect quality dynamically.
#ffmpeg -i "$1" -ab 192k "$1.mp3"

TEMP=`mktemp "$1.XXXX"`
#TEMP="${TEMP}.wav"
rm "${TEMP}"

ffmpeg -i "$1" -sameq -f wav "${TEMP}"

# VBR to the rescue!
lame --preset extreme "${TEMP}" "${1}.mp3"
rm "${TEMP}"