#!/bin/bash

# Usage: waltzify file.mp3 beats.json

# TODO: Cache JSON by file hash  (what does Echonest use?)

if [ "${2}" = "" ]
then
  JSON_FILE="${1}.json"
  echo "JSON file not passed in. Assuming: ${JSON_FILE}"
else
  JSON_FILE="${2}"
  echo "JSON file passed in: ${JSON_FILE}"
fi

if [ ! -f "${JSON_FILE}" ]
then
  echo "JSON file (${JSON_FILE}) does not exist. Analyzing ${1} using Echonest..."
    analyze -v "${1}"
    JSON_FILE="${1}.json"
fi


MUSIC_FILE_IN="${1}"

TIME=$(date "+%Y-%m-%d at %H-%M-%S")
MUSIC_FOLDER_TEMP=`mktemp "${MUSIC_FILE_IN}.${TIME}.XXXX"`
rm "${MUSIC_FOLDER_TEMP}"
mkdir "${MUSIC_FOLDER_TEMP}"
cp "${MUSIC_FILE_IN}"  "${MUSIC_FOLDER_TEMP}/${MUSIC_FILE_IN}"

ffmpeg -i "${MUSIC_FOLDER_TEMP}/${MUSIC_FILE_IN}" -sameq -f wav "${MUSIC_FOLDER_TEMP}/${MUSIC_FILE_IN}.wav"

MUSIC_FILE="${MUSIC_FOLDER_TEMP}/${MUSIC_FILE_IN}.wav"



waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 5 0 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 5 1 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 5 2 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 5 3 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 5 4 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 5 5 6&

waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 100 0 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 100 1 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 100 2 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 100 3 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 100 4 6&
waltz_blender "${MUSIC_FILE}" "${JSON_FILE}" "1234[56]" 100 5 6&